---
title: "Review of R tracking packages"
author: "Rocio Joo"
date: "January 31st, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


A pre-print of our work reviewing R tracking packages is available here: https://arxiv.org/abs/1901.05935. 

We review R packages for processing or analysis of tracking data as an introduction to this
set of packages for researchers and provide feedback and recommendations to package developers, from a user perspective. 

The set of tracking packages reviewed here is a subset of the ones in the survey (see last post $\textit{there should be a link}). If you have read the previous post, this next explanation is for you. 

For the survey, we considered packages created with the main purpose of 1) processing or analyzing data obtained from devices used to track organisms, or 2) analyze tracking data in general. Tracking data would have space and time components, i.e. at least (x,y,t), or assuming t as a general index in regular steps. 
Using that definition of tracking data, accelerometry data, for example, would not be tracking data (it doesn't have a 2D spatial component), but it would be obtained from devices used to track organisms. Because it falls under the first condition, packages dealing with accelerometry data only were considered for the survey. The same happened with packages handling time-depth-recorder (TDR) data. 

In the manuscript, we reviewed only packages that were created to either analyze tracking data or to transform data from tagging devices into proper tracking data. For instance, a package that would use accelerometer, gyroscope and magnetometer data to reconstruct an animal's trajectory via path integration, thus transforming those data into an (x,y,t) format, would fit into the definition. But a package analyzing accelerometry series to detect changes in behavior would not fit. We made a small section to mention these packages, but the review is not centered on them. 

From the $72$ packages listed for the survey, $57$ were included in the review. These were $15$ left behind:

* $\texttt{acc}$, $\texttt{accelerometry}$, $\texttt{GGIR}$, $\texttt{nparACT}$, $\texttt{pawacc}$ and $\texttt{PhysicalActivity}$: accelerometry packages
* 
$6$ of them were accelerometry packages (), one was a TDR package ($\texttt{diveMove}$), one analyzes both TDR and accelerometer data {$\texttt{rbl}$}, "one"


1. The advent of miniaturized biologging devices has provided ecologists
with unparalleled opportunities to record animal movement across scales,
and led to the collection of ever-increasing quantities of tracking data.
In parallel, sophisticated tools to process, visualize and analyze tracking
data have been developed in abundance. Within the R software alone,
we listed 57 focused on these tasks, called here tracking packages.
2. Here, we reviewed these tracking packages, as an introduction to this
set of packages for researchers, and to provide feedback and recommen-
dations to package developers, from a user perspective. We described
each package based on a workflow centered around tracking data (i.e.
(x, y, t)), broken down in three stages: pre-processing, post-processing,
and analysis (data visualization, track description, path reconstruction,
behavioral pattern identification, space use characterization, trajectory
simulation and others).
3. Supporting documentation is key to the accessibility of a package for
users. Based on a user survey, we reviewed the quality of packages’
documentation, and identified 12 packages with good or excellent docu-
mentation.
4. Links between packages were assessed through a network graph analysis.
Although a large group of packages shows some degree of connectivity
(either depending on functions or suggesting the use of another tracking
package), a third of tracking packages work on isolation, reflecting a
fragmentation in the R Movement-Ecology programming community.
5. Finally, we provide recommendations for users to choose packages, and
for developers to maximize usefulness of their contribution and strengthen
the links between the programming community.
## A large amount of R packages for movement and the need for a survey

The use of tracking devices is increasing as a consequence of the development of new and cheaper loggers. With large amounts of available data, more sophisticated tools to process, visualize and analyze data are being developed. One of the most used programming softwares for this matter is the free open source R software. We have identified more than 70 R packages created for that purpose! The large amount of existent packages makes it difficult to keep track of the spectrum of choices. For that reason, we aimed at assessing the current state of the art of the movement-related R packages regarding

    1. How popular those packages are; 
    2. How well documented they are; 
    3. How relevant they are for users. 
    
Those were the three questions that we asked about the packages, plus one about the level as an R user of the survey participant. We will go to the details of each question later in this post. 

## Packages included in the survey

In theory, any package could be potentially useful for movement analysis; either a time series package, a spatial analysis one or even $\texttt{ggplot2}$ to make more beautiful graphics! For this survey, we considered only packages created with the main purpose of 1) processing or analyzing data obtained from devices used to track organisms, or 2) analyze tracking data in general. Tracking data would have space and time components, i.e. at least (x,y,t), or assuming t as a general index in regular steps. 

These packages are: $\texttt{acc}$, $\texttt{accelerometry}$, $\texttt{adehabitatHR}$, $\texttt{adehabitatHS}$, $\texttt{adehabitatLT}$, $\texttt{amt}$, $\texttt{animalTrack}$, $\texttt{anipaths}$, $\texttt{argosfilter}$, $\texttt{argosTrack}$, $\texttt{BayesianAnimalTracker}$, $\texttt{BBMM}$, $\texttt{bcpa}$, $\texttt{bsam}$, $\texttt{caribou}$, $\texttt{crawl}$, $\texttt{ctmcmove}$, $\texttt{ctmm}$, $\texttt{diveMove}$, $\texttt{drtracker}$, $\texttt{EMbC}$, $\texttt{feedR}$, $\texttt{FLightR}$, $\texttt{GeoLight}$, $\texttt{GGIR}$, $\texttt{hab}$, $\texttt{HMMoce}$, $\texttt{Kftrack}$, $\texttt{m2b}$, $\texttt{marcher}$, $\texttt{migrateR}$, $\texttt{mkde}$, $\texttt{momentuHMM}$, $\texttt{move}$, $\texttt{moveHMM}$, $\texttt{movement}$, $\texttt{movementAnalysis}$, $\texttt{moveNT}$, $\texttt{moveVis}$, $\texttt{moveWindSpeed}$, $\texttt{nparACT}$, $\texttt{pathtrackr}$, $\texttt{pawacc}$, $\texttt{PhysicalActivity}$, $\texttt{probgls}$, $\texttt{rbl}$, $\texttt{recurse}$, $\texttt{rhr}$, $\texttt{rpostgisLT}$, $\texttt{rsMove}$, $\texttt{SDLfilter}$, $\texttt{SGAT/TripEstimation}$, $\texttt{sigloc}$, $\texttt{SimilarityMeasures}$, $\texttt{SiMRiv}$, $\texttt{smam}$, $\texttt{SwimR}$, $\texttt{T-LoCoH}$, $\texttt{telemetr}$, $\texttt{trackdem}$, $\texttt{trackeR}$, $\texttt{Trackit}$, $\texttt{TrackReconstruction}$, $\texttt{TrajDataMining}$, $\texttt{trajectories}$, $\texttt{trip}$, $\texttt{TwGeos/BAStag}$, $\texttt{TwilightFree}$, $\texttt{Ukfsst/kfsst}$, $\texttt{VTrack}$ and $\texttt{wildlifeDI}$.

Packages from any public repository (e.g. CRAN, GitHub, R-forge) were included in the survey. Packages created for eye, computer-mouse or fishing vessel movement were not considered here (but you are welcome to make your own survey about them!). 

Note: $\texttt{trajr}$ was added to the survey in a late stage, but because of that, and the fact that it got only one response, we filtered it out of the analysis.
